-- 4. (8 points) Display all invoice items per billing account, showing the billing plan name and fee amount at the
-- time when the invoice item was generated. Sort the invoice items by account id and then datetime created, and only
--  display invoice items generated by plans with an interval reference code of "monthly" or "30_day".
--  Show the billing account customer id; the invoice item id, charge amount and item creation datetime in the Billing System,
--  and the datetime of its insertion into the Data Vault; and the plan period fee, name, type, interval reference code, and
--  datetime of the plan's last change prior to the time when the invoice item was generated.Hint 1: go through a subscription
--  record to get to the plan.Hint 2: you'll want to ensure that the plan satellite record's created_at <= item hub record's created_at.
--

-- ALL VALUES FOR BILLING_HUB_ID AND SUBSCRIPTION_HUB_ID ARE NULL OR BLOB WHICH AND ARE KEY TO SOLVE THIS QUESTION.

SELECT

subs_sat.fk_x_subscription_hub_id,
plan_sat.period_fee_amt,
plan_sat.name,
plan_sat.fk_r_plan_type_ref_cd,
plan_sat.fk_r_plan_interval_ref_cd

FROM v_x_subscription_r_plan_lnk AS s_p_link

RIGHT JOIN v_r_plan_sat AS plan_sat

#did a right join because the plan hub/sat has more DISTINCT entries than the link total rows?

ON plan_sat.fk_r_plan_hub_id = s_p_link.fk_r_plan_hub_id

LEFT JOIN v_x_subscription_sat as subs_sat

ON s_p_link.fk_x_subscription_hub_id = subs_sat.fk_x_subscription_hub_id

#Just to replicate similar logic in expected query, I'll order by plan_hub_id , and by created datetime

WHERE plan_sat.fk_r_plan_interval_ref_cd = 'monthly' OR plan_sat.fk_r_plan_interval_ref_cd = '30_day'

ORDER BY subs_sat.fk_x_subscription_hub_id, subs_sat.created_at DESC
