1. (2 points) Compute the minimum, maximum, average, and standard deviation of the charge amount of the complete set of invoice items,
but only take into account the very last version of each invoice item. Show your answers in dollars, not cents.
Hint: be sure to understand the relationship between the various views and their non-view counterparts.


2. (3 points) Compute the minimum, maximum, average, and standard deviation of the period duration in days, of the complete set of invoice
items, grouping by whether or not the invoice item represented a prorated charge. As before, only take into account the very last version
of each invoice item. Show your answers in days.

3. (5 points) Join the invoice items to their parent invoices and compute the min, max, average, and standard deviation of the distinct
number of invoice lines per invoice. As before, only take into account the very last version of each invoice item and parent invoice.
In addition, restrict the computation to invoice lines coming from a revenue source with reference code of "PRIMARY".
Do not take into account any parent invoices without invoice lines.

4. (8 points) Display all invoice items per billing account, showing the billing plan name and fee amount at the time when the invoice
 item was generated. Sort the invoice items by account id and then datetime created, and only display invoice items generated by plans
  with an interval reference code of "monthly" or "30_day".
  Show the billing account customer id; the invoice item id, charge amount and item creation datetime in the Billing System, and the
  datetime of its insertion into the Data Vault; and the plan period fee, name, type, interval reference code, and datetime of the plan's
  last change prior to the time when the invoice item was generated.Hint 1: go through a subscription record to get to the plan.
  Hint 2: you'll want to ensure that the plan satellite record's created_at <= item hub record's created_at.



SHOW COUNT FOR EACH INVOICE

  select v_x_invoice_hub.sk_id as invoice_id, count(v_x_invoice_x_invoice_item_lnk.fk_x_invoice_item_hub_id) as items_id
  from v_x_invoice_hub
  join v_x_invoice_x_invoice_item_lnk
  on v_x_invoice_hub.sk_id = v_x_invoice_x_invoice_item_lnk.fk_x_invoice_hub_id

  GROUP BY v_x_invoice_hub.sk_id

  create view invoice_id_and_item_id as
  select v_x_invoice_hub.sk_id as invoice_id, v_x_invoice_x_invoice_item_lnk.fk_x_invoice_item_hub_id as item_id
  from v_x_invoice_hub

  join v_x_invoice_x_invoice_item_lnk
  on v_x_invoice_hub.sk_id = v_x_invoice_x_invoice_item_lnk.fk_x_invoice_hub_id
